### ISSUE TITLE
Custom Credit GUI Glitch

### ISSUE THREAD

**Issue by kenijey** [kamildanak/EnderPay#6]
if you change the GUI scale it will go other places on screen :/ like this
for example i designed it to look like this:(near the slotbar)
![2017-03-17_14 57 12](https://cloud.githubusercontent.com/assets/24831406/24042253/d6b032ac-0b19-11e7-9f9e-b4da56e0e0d2.png)
but if i change the gui it will be like this:
![2017-03-17_14 57 17](https://cloud.githubusercontent.com/assets/24831406/24042265/e40df8e4-0b19-11e7-8aba-9b08712c38bf.png)
**Why** i am making this a problem, because the other users which have different screen resolution, and a different gui scale users, will have problems. And i already see it on my friends computer. Can you make a custom place like in the first picture? I think it's better in there. Or can you add a config to set a custom location by respect to the **hotbar**? Thanks. Using 1.11.2.

**Comment by kamildanak** [comment]
Fixed in 02f5cdbf9ef345d2662dff9a4a9a5dc163003b7e. It is now possible to choose one of the following positions:
"top_left", "middle_left", "bottom_left", "top_middle", "middle_middle", "bottom_middle", "top_right", "middle_right", "bottom_right", "hud_above_left", "hud_above_middle", "hud_above_right".
Additionaly, the anchor of widget can be set to: "left", "centre" or "right".
To achieve result depicted on first image the following options should be set:
S:anchorHUD=left, S:position=bottom_middle, I:xOffset=92, I:yOffset=-14

**Comment by kenijey** [comment]
thanks a lot!
